# Generated by Django 5.2.4 on 2025-08-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.URLField(max_length=1000)),
                ('file_type', models.CharField(choices=[('image', '画像'), ('video', '動画'), ('audio', '音声'), ('other', 'その他')], default='other', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['file_type', 'upload_date'], name='archive_app_file_ty_3d231f_idx')],
            },
        ),
    ]
