services:
  - type: web
    name: file-mapping-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn archive_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER
        value: True
      - key: DATABASE_URL
        # ここにSupabaseのデータベース接続URLを貼り付けてください。
        # 例: postgresql://postgres:[YOUR_PASSWORD]@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
        value: "postgresql://postgres.ccjipkceqlrnqbcifjjl:yuya1652@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres" # <-- ここをSupabaseのURLに置き換えてください
      - key: ALLOWED_HOSTS
        value: ".onrender.com"