databases:
  - name: archive-db
    databaseName: archive_db
    user: archive_user
    plan: free

services:
  - type: web
    name: file-mapping-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn archive_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER
        value: True
      - key: DATABASE_URL
        fromDatabase:
          name: archive-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 